name: Acceptance Tests

on:
  pull_request:
    branches: [main, release/**]
  push:
    branches: [main, release/**]
    tags: [v*]

permissions:
  checks: write
  contents: read

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  acceptance_tests:
    name: ${{ matrix.test.name }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        test:
          - { name: 'API Batch 1', testfilter: 'api_batch1' }
          - { name: 'API Batch 2', testfilter: 'api_batch2' }
          - { name: 'API Batch 3', testfilter: 'api_batch3' }
          - { name: 'Debug API', testfilter: 'debug' }
          - { name: 'ERC20', testfilter: 'erc20' }
          - { name: 'Rate Limiter', testfilter: 'ratelimiter', test_ws_server: true, test_rate_limits: true }
          - { name: 'SendRawTransaction Extension', testfilter: 'send_raw_transaction_extension' }
          - { name: 'HBar Limiter Batch 1', testfilter: 'hbarlimiter_batch1' }
          - { name: 'HBar Limiter Batch 2', testfilter: 'hbarlimiter_batch2' }
          - { name: 'HBar Limiter Batch 3', testfilter: 'hbarlimiter_batch3' }
          - { name: 'Token Create', testfilter: 'tokencreate' }
          - { name: 'Token Management', testfilter: 'tokenmanagement' }
          - { name: 'Precompile', testfilter: 'htsprecompilev1' }
          - { name: 'Precompile Calls', testfilter: 'precompile-calls' }
          - { name: 'Websocket Batch 1', testfilter: 'ws_batch1', test_ws_server: true }
          - { name: 'Websocket Batch 2', testfilter: 'ws_batch2', test_ws_server: true }
          - { name: 'Websocket Batch 3', testfilter: 'ws_batch3', test_ws_server: true }
          - { name: 'Sub Tinybar Monetary Precision', testfilter: 'sub_tinybar_monetary_precision' }
          - { name: 'Cache Service', testfilter: 'cache-service' }
          - { name: 'Protocol Account Service', testfilter: 'protocol-account-service', test_ws_server: true }
          - { name: 'Protocol Block Service', testfilter: 'protocol-block-service', test_ws_server: true }
          - { name: 'Protocol Common Service', testfilter: 'protocol-common-service', test_ws_server: true }
          - { name: 'Protocol Contract Service', testfilter: 'protocol-contract-service', test_ws_server: true }
          - { name: 'Protocol Transaction Service', testfilter: 'protocol-transaction-service', test_ws_server: true }
          - { name: 'Protocol Fee Service', testfilter: 'protocol-fee-service', test_ws_server: true }
          - {
              name: 'Protocol Eth Plain',
              testfilter: 'protocol-eth-plain',
              test_ws_server: true,
              test_rate_limits: true,
            }
          - { name: 'Server Config', testfilter: 'serverconfig' }
          - { name: 'Semantics and varying response status', testfilter: 'json_rpc_compliance' }
          - name: "Semantics and default OK response status"
            testfilter: "json_rpc_compliance"
            on_valid_json_rpc_http_response_status_code: 200
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: ${{ matrix.test.testfilter }}
      test_ws_server: ${{ matrix.test.test_ws_server || false }}
      test_rate_limits: ${{ matrix.test.test_rate_limits || false }}
      on_valid_json_rpc_http_response_status_code: ${{ matrix.test.on_valid_json_rpc_http_response_status_code || 400 }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish_results:
    name: Publish Results
    if: ${{ github.actor != 'dependabot[bot]' && !cancelled() }}
    needs: [acceptance_tests]
    runs-on: hiero-smart-contracts-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Download Test Reports
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: Test Results (*)
          merge-multiple: true

      - name: Publish Test Report
        uses: step-security/publish-unit-test-result-action@681100d67b09305624c089873f12c545ee7cbc24 # v2.23.0
        with:
          check_name: '' # Set to empty to disable check run
          json_thousands_separator: ','
          files: 'test-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
