name: Acceptance Tests on Public Network

on:
  workflow_dispatch:
    inputs:
      operator_id:
        description: 'The Account ID of the operator'
        required: true
        type: string
      operator_key:
        description: 'The ED25519 or ECDSA  DER encoded private key of the operator'
        required: true
        type: string
      network:
        description: 'The public network to run the tests against'
        required: true
        type: choice
        options:
          - mainnet
          - testnet
          - previewnet

permissions:
  contents: read

jobs:
  release-tests:
    name: Release Tests
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: release_light
      envfile: ${{ inputs.network }}Acceptance.env
      operator_id: ${{ inputs.operator_id }}
    secrets:
      operator_key: ${{ inputs.operator_key }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish_results:
    name: Publish Results
    if: ${{ !cancelled() }}
    needs:
      - release-tests
    runs-on: hiero-smart-contracts-linux-medium
    permissions:
      checks: write
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Download Test Reports
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: Test Results (*)
          merge-multiple: true

      - name: Publish Test Report
        uses: step-security/publish-unit-test-result-action@681100d67b09305624c089873f12c545ee7cbc24 # v2.23.0
        with:
          check_name: Test Results
          json_thousands_separator: ','
          files: 'test-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
