name: Hoppscotch Endpoint Tests

on:
  pull_request:
    branches:
      - main
      - release/**
  push:
    branches:
      - main
      - release/**
    tags:
      - v*
  workflow_dispatch:
    inputs:
      networkTag:
        description: 'Hedera network node image tag'
        required: false
        type: string
      mirrorTag:
        description: 'Hedera mirror node image tag'
        required: false
        type: string
      soloVersion:
        description: 'Solo version'
        required: false
        type: string

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup-local-hedera:
    name: Hoppscotch Endpoint Tests
    runs-on: hiero-smart-contracts-linux-medium
    permissions:
      contents: write
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make gcc g++

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22

      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install packages
        run: npm ci

      - name: Create .env file
        run: cp ./tests/server/localAcceptance.env .env

      - name: Build Typescript
        run: npm run build

      - name: Generate falcon-values config file
        run: |
          cat > .github/falcon.yml <<EOF
          network:
            --consensus-node-version: "${{ inputs.networkTag || 'v0.77.0-rc.6' }}"
            --node-aliases: "node1"
          setup:
            --consensus-node-version: "${{ inputs.networkTag || 'v0.77.0-rc.6' }}"
            --node-aliases: "node1"
          consensusNode:
            --node-aliases: "node1"
          mirrorNode:
            --enable-ingress: true
            --pinger: true
            --mirror-node-version: "${{ inputs.mirrorTag || 'v0.162.0' }}"
            --values-file: .github/mirror-node-values.yaml
          EOF

      - name: Setup Kind
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          install_only: true
          node_image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
          version: v0.29.0
          kubectl_version: v1.32.5
          verbosity: 3
          wait: 120s

      - name: Start the solo node
        env:
          MIRROR_NODE_PORT: 5551
          GRPC_LOCAL_PORT: 50211
        run: |
          npx @hashgraph/solo@${{ inputs.soloVersion || '0.85.0' }} one-shot falcon deploy \
            --values-file .github/falcon.yml \
            --external-address 0.0.0.0 \
            --dev \
            --deploy-explorer=false \
            --deploy-relay=false
        timeout-minutes: 15

      - name: Start Redis
        run: docker run -d --name redis -p 6379:6379 redis:7-alpine

      - name: Start the local relay
        run: npm run start &

      - name: Run Hoppscotch Tests
        run: npm run hopp
