name: Release Branch Automation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (semver ie. 0.24.0):'
        type: string
        required: true

jobs:
  branch_bump_tag:
    runs-on: hiero-smart-contracts-linux-medium
    env:
      RELEASE_NOTES_FILENAME: release_notes
    outputs:
      create_pr: ${{ env.CREATE_PR }}
      next_version_snapshot: ${{ env.NEXT_VERSION_SNAPSHOT }}
      pr_title: ${{ env.PR_TITLE }}
      release_branch: ${{ env.RELEASE_BRANCH }}
      milestone: ${{ env.MILESTONE }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Parse Version
        id: version_parser
        uses: step-security/semver-utils@5bb182a08240146b23b61cc002cb74004377da4b # v5.0.0
        with:
          lenient: false
          version: ${{ github.event.inputs.version }}

      - name: Set Release Environment Variables
        run: |
          PREMINOR_VERSION=${{ steps.version_parser.outputs.inc-preminor }}
          NEXT_VERSION_SNAPSHOT=${PREMINOR_VERSION//-0/-SNAPSHOT}
          RELEASE_BRANCH="release/${{ steps.version_parser.outputs.major }}.${{ steps.version_parser.outputs.minor }}"
          [[ -z "${{ steps.version_parser.outputs.prerelease }}" ]] && \
            VERSION=${{ steps.version_parser.outputs.release }} || \
            VERSION="${{ steps.version_parser.outputs.release }}-${{ steps.version_parser.outputs.prerelease }}"
          RELEASE_TAG="v${VERSION}"
          cat >> $GITHUB_ENV <<EOF
          NEXT_VERSION_SNAPSHOT=$NEXT_VERSION_SNAPSHOT
          RELEASE_BRANCH=$RELEASE_BRANCH
          RELEASE_TAG=$RELEASE_TAG
          VERSION=$VERSION
          MILESTONE=${{ steps.version_parser.outputs.release}}
          EOF

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@c0b4a334b9b72bfaaebec86ef022a78a5b17f828 # v7.0.0
        with:
          git_commit_gpgsign: true
          git_committer_email: ${{ vars.GIT_USER_EMAIL }}
          git_committer_name: ${{ vars.GIT_USER_NAME }}
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}

      - name: Create and Switch to Release Branch
        run: |
          if ! git ls-remote --exit-code --heads --quiet origin refs/heads/${RELEASE_BRANCH}; then
            git checkout -b ${RELEASE_BRANCH}
            git push -u origin ${RELEASE_BRANCH}

            # create a PR to bump main branch to the next snapshot version
            echo "CREATE_PR=true" >> $GITHUB_ENV
            echo "PR_TITLE=chore(release): Bump versions for v$NEXT_VERSION_SNAPSHOT" >> $GITHUB_ENV
          else
            git checkout ${RELEASE_BRANCH}
          fi

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22

      - name: Install make
        run: sudo apt-get update; sudo apt-get install build-essential -y

      - name: Install dependencies
        run: npm ci

      - name: Build Typescript
        run: npm run build

      - name: Bump Versions
        run: npm run bump-version --semver=${{ env.VERSION }}

      - name: Close the Milestone
        if: ${{ steps.version_parser.outputs.prerelease == '' }}
        id: milestone
        uses: step-security/close-milestone@d6e3b63e31f1f869bd3d0403f8cdc1a68f59ab4a # v2.2.2
        with:
          milestone_name: ${{ steps.version_parser.outputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Notes
        if: ${{ steps.milestone.outputs.milestone_id != '' }}
        uses: step-security/release-notes-generator-action@7df92b9170c5723a5fcb119dbc4cf891d2bac1fe # v3.2.4
        env:
          FILENAME: ${{ env.RELEASE_NOTES_FILENAME }}
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          MILESTONE_NUMBER: ${{ steps.milestone.outputs.milestone_id }}

      - name: Commit and Tag
        uses: step-security/git-auto-commit-action@749bc1cc775376092cc4227ba537137f445ca7c3 # v7.1.1
        with:
          commit_author: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          commit_message: 'chore(release): Bump versions for ${{ env.RELEASE_TAG }}'
          commit_options: '--no-verify --signoff --gpg-sign'
          commit_user_name: ${{ steps.gpg_importer.outputs.name }}
          commit_user_email: ${{ steps.gpg_importer.outputs.email }}
          tagging_message: ${{ env.RELEASE_TAG }}

      - name: Create Github Release
        uses: step-security/release-action@a0d8e0f90f554c15366ca2c9046bf4090d24adbe # v1.21.0
        with:
          bodyFile: ${{ env.RELEASE_NOTES_FILENAME }}.md
          commit: ${{ env.RELEASE_BRANCH }}
          draft: true
          name: ${{ env.RELEASE_TAG }}
          omitBody: ${{ steps.milestone.outputs.milestone_id == '' }}
          prerelease: ${{ steps.version_parser.outputs.prerelease != '' }}
          tag: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}

  create_snapshot_pr:
    name: Create snapshot PR
    runs-on: hiero-smart-contracts-linux-medium
    needs: branch_bump_tag
    if: ${{ needs.branch_bump_tag.outputs.create_pr == 'true' }}
    env:
      NEXT_VERSION_SNAPSHOT: ${{ needs.branch_bump_tag.outputs.next_version_snapshot }}
      RELEASE_BRANCH: ${{ needs.branch_bump_tag.outputs.release_branch }}
      PR_TITLE: ${{ needs.branch_bump_tag.outputs.pr_title }}
      MILE_STONE: ${{ needs.branch_bump_tag.outputs.milestone }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@c0b4a334b9b72bfaaebec86ef022a78a5b17f828 # v7.0.0
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22

      - name: Install make
        run: sudo apt-get update; sudo apt-get install build-essential -y

      - name: Install dependencies
        run: npm ci

      - name: Build Typescript
        run: npm run build

      - name: Bump Versions
        run: npm run bump-version --semver=${{ env.NEXT_VERSION_SNAPSHOT }} --snapshot=true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          body: |
            **Description**:
            Bump versions for v${{ env.NEXT_VERSION_SNAPSHOT }}
            Automated snapshot version bump for the next development cycle.

            **Related issue(s)**:
          branch: create-pull-request/${{ env.NEXT_VERSION_SNAPSHOT }}
          commit-message: ${{ env.PR_TITLE }}
          committer: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          author: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          delete-branch: true
          signoff: true
          title: ${{ env.PR_TITLE }}
          milestone: ${{ env.MILE_STONE }}
          labels: 'process'
          assignees: 'swirlds-automation'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
